### ISSUE TITLE
Rika2Mqtt Stop working when using decimals with temperatureOffset

### ISSUE THREAD

**Issue by sebastienvermeille** [sebastienvermeille/rika2mqtt#139]
I discovered a nasty bug when playing with my RIKA stove.

I setted an offset for the remote temperature sensor -0.5 and this break up rika2mqtt deserialization.

Logs:
```
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was -0.5 at line 1 column 959 path $.controls.temperatureOffset
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:251)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:241)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at dev.cookiecode.rika2mqtt.rika.firenet.RikaFirenetServiceImpl.getStatus(RikaFirenetServiceImpl.java:293)
        at dev.cookiecode.rika2mqtt.bridge.Bridge.lambda$publishToMqtt$0(Bridge.java:125)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at dev.cookiecode.rika2mqtt.bridge.Bridge.publishToMqtt(Bridge.java:120)
        at dev.cookiecode.rika2mqtt.bridge.Bridge.init(Bridge.java:88)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219)
        ... 23 common frames omitted
Caused by: java.lang.NumberFormatException: Expected an int but was -0.5 at line 1 column 959 path $.controls.temperatureOffset
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1218)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:249)
        ... 44 common frames omitted
```

**Comment by sebastienvermeille** [comment]
I will work on it in a couple of hours and provide a release as soon as I merged it.
